### ISSUE TITLE
uploading

### ISSUE THREAD

**Issue by Jake-Lofthouse** [nygma2004/locoremote#1]
how do I upload this to the esp32?

**Comment by nygma2004** [comment]
This is the complete source code. You need to build it in Arduino IDE and upload it to the ESP. I will check how I can also release a binary version which can simply be uploaded with a tool. That would be much easier. But I have never done anything like that before.

**Comment by Jake-Lofthouse** [comment]
ok thank you

i'am looking forward to hearing more about this binary version!
